In [1]:
import pandas as pd
import plotly.express as px

In [2]:
dyahoo = pd.read_excel('../dataset/BTC Price History & Historical Data - Yahoo Finance.ods', engine='odf')
dcmc = pd.read_csv('../dataset/Bitcoin_01_01_2009-01_01_2025_historical_data_coinmarketcap.csv', delimiter=';')
dcoingecko = pd.read_csv('../dataset/btc-usd-max (coingecko).csv')

In [3]:
pd.options.display.float_format = '{:,.2f}'.format

## 1. Formatação do dataset Yahoo

In [ ]:
dyahoo.dtypes

In [ ]:
dyahoo['Date'] = pd.to_datetime(dyahoo['Date'])
dyahoo['Date'] = dyahoo['Date'].dt.strftime('%Y-%d-%m')

In [ ]:
dyahoo['Volume'] = dyahoo['Volume'].astype(float)

In [ ]:
dyahoo

In [ ]:
dyahoo[dyahoo['Date'] == '2024-01-02']

In [ ]:
dyahoo_formatado = dyahoo.sort_values(by='Date').reset_index(drop=True)
dyahoo_formatado

In [ ]:
desenvolvimento_volume_yahoo = px.line(dyahoo_formatado, title='Média de desenvolvimento de volume no decorrer dos meses',
                                       x='Date', y='Volume', log_y=True)
desenvolvimento_volume_yahoo

## 2. Formatação do dataset CoinMarketCap

## Transformação de dados

### Drop, Rename & Replace

In [4]:
dcmc_formatada = dcmc.drop(columns=['timeClose', 'timeHigh', 'timeLow', 'name', 'timestamp'])

In [5]:
dcmc_formatada = dcmc_formatada.rename(columns={'timeOpen':'data'})

In [6]:
dcmc_formatada['data'] = dcmc_formatada['data'].str.replace('T00:00:00.000Z', '')

### Criação de colunas

In [7]:
dcmc_formatada['data'] = pd.to_datetime(dcmc_formatada['data'])

In [8]:
dcmc_formatada['mês'] = dcmc_formatada['data'].dt.month

In [9]:
dcmc_formatada['ano'] = dcmc_formatada['data'].dt.year

In [10]:
calculo_variacao = dcmc_formatada['close']/dcmc_formatada['open']-1
dcmc_formatada['var%'] = calculo_variacao*100

dcmc_formatada['var%'] = dcmc_formatada['var%'].astype(str)
dcmc_formatada

,data,open,high,low,close,volume,marketCap,circulatingSupply,mês,ano,var%
0,2025-01-01,"93,425.10","109,114.88","89,260.10","102,405.03","1,917,584,997,242.14","2,029,428,972,448.10",19817771,1,2025,9.611897384194524
1,2024-12-01,"96,461.34","108,268.45","91,317.14","93,429.20","2,367,571,853,073.27","1,850,183,342,119.26",19803921,12,2024,-3.1433671659751417
2,2024-11-01,"70,216.90","99,655.50","66,803.65","96,449.06","2,214,093,389,107.44","1,908,652,965,665.17",19789534,11,2024,37.35875548144687
3,2024-10-01,"63,335.60","73,577.21","58,895.21","70,215.19","1,049,276,385,591.06","1,388,607,599,014.43",19775975,10,2024,10.862108608108944
4,2024-09-01,"58,969.80","66,480.69","52,598.70","63,329.50","935,228,464,018.62","1,251,461,875,405.87",19761121,9,2024,7.393104124935457
...,...,...,...,...,...,...,...,...,...,...,...
137,2013-08-01,106.21,140.89,101.21,135.35,0.00,"1,574,672,051.25",11634075,8,2013,27.43262064929455
138,2013-07-01,97.51,111.34,65.53,106.09,0.00,"1,218,777,833.50",11488150,7,2013,8.799091389328083
139,2013-06-01,128.82,129.78,88.50,96.61,0.00,"1,096,957,771.35",11354025,6,2013,-24.997867808874773
140,2013-05-01,139.00,139.89,79.10,129.00,0.00,"1,447,870,200.00",11223800,5,2013,-7.194244604316546
141,2013-04-01,135.30,147.49,132.10,139.00,0.00,"1,542,813,125.00",11099375,4,2013,2.7346613930107955

### Alteração de tipos

In [11]:
dcmc_formatada[['volume', 'marketCap']] = dcmc_formatada[['volume', 'marketCap']].astype(int)

In [12]:
dcmc_formatada['volume'] = dcmc_formatada['volume'].astype(float)
dcmc_formatada['marketCap'] = dcmc_formatada['marketCap'].astype(float)

In [ ]:
dcmc_formatada.dtypes

In [13]:
dcmc_formatada.sort_values(by= 'data', ascending=False)

,data,open,high,low,close,volume,marketCap,circulatingSupply,mês,ano,var%
0,2025-01-01,"93,425.10","109,114.88","89,260.10","102,405.03","1,917,584,997,242.00","2,029,428,972,448.00",19817771,1,2025,9.611897384194524
1,2024-12-01,"96,461.34","108,268.45","91,317.14","93,429.20","2,367,571,853,073.00","1,850,183,342,119.00",19803921,12,2024,-3.1433671659751417
2,2024-11-01,"70,216.90","99,655.50","66,803.65","96,449.06","2,214,093,389,107.00","1,908,652,965,665.00",19789534,11,2024,37.35875548144687
3,2024-10-01,"63,335.60","73,577.21","58,895.21","70,215.19","1,049,276,385,591.00","1,388,607,599,014.00",19775975,10,2024,10.862108608108944
4,2024-09-01,"58,969.80","66,480.69","52,598.70","63,329.50","935,228,464,018.00","1,251,461,875,405.00",19761121,9,2024,7.393104124935457
...,...,...,...,...,...,...,...,...,...,...,...
137,2013-08-01,106.21,140.89,101.21,135.35,0.00,"1,574,672,051.00",11634075,8,2013,27.43262064929455
138,2013-07-01,97.51,111.34,65.53,106.09,0.00,"1,218,777,833.00",11488150,7,2013,8.799091389328083
139,2013-06-01,128.82,129.78,88.50,96.61,0.00,"1,096,957,771.00",11354025,6,2013,-24.997867808874773
140,2013-05-01,139.00,139.89,79.10,129.00,0.00,"1,447,870,200.00",11223800,5,2013,-7.194244604316546
141,2013-04-01,135.30,147.49,132.10,139.00,0.00,"1,542,813,125.00",11099375,4,2013,2.7346613930107955

### Funções para filtragem de meses negativos e positivos

In [14]:
meses = list(range(1, 13))

In [16]:
def EncontrarMes(df, valor):
    return df.loc[df['mês'].isin(valor)]
dados_brutos = EncontrarMes(dcmc_formatada, meses)

### Filtragem de valores negativos e positivos

In [17]:
dataframe_negativo = pd.DataFrame(dados_brutos[dados_brutos['var%'].str.contains('-')])
dataframe_negativo['var%'] = dataframe_negativo['var%'].astype(float)

In [18]:
dataframe_negativo[dataframe_negativo['ano'] == 2015]

,data,open,high,low,close,volume,marketCap,circulatingSupply,mês,ano,var%
113,2015-08-01,284.69,285.71,199.57,230.06,"20,710,700.00","3,349,845,416.00",14561000,8,2015,-19.19
116,2015-05-01,235.94,247.80,228.57,230.19,"14,730,800.00","3,273,756,425.00",14221975,5,2015,-2.44
117,2015-04-01,244.22,261.80,214.87,236.15,"33,818,600.00","3,332,094,504.00",14110375,4,2015,-3.31
118,2015-03-01,254.28,300.04,236.51,244.22,"22,672,000.00","3,420,112,896.00",14004000,3,2015,-3.96
120,2015-01-01,320.43,320.43,171.51,217.46,"23,348,200.00","2,997,692,310.00",13784775,1,2015,-32.13

In [ ]:
dataframe_con = pd.DataFrame(dados_brutos)
dataframe_con['var%'] = dataframe_con['var%'].astype(float)

dataframe_positivo = dataframe_con[dataframe_con['var%'] >= 0]

In [ ]:
dataframe_positivo[dataframe_positivo['ano'] == 2015]

## Média de volume anual

### Média anual de volume de meses com baixo desempenho
Os válores são influenciados pela quantidade de meses negativos e positivos de um determinado ano. Caso um ano tenha mais meses positivos do que negativos, a tendencia é que a **média de volume anual de meses com baixo desempenho** seja menor

In [ ]:
dataframe_negativo.groupby('ano')['volume'].mean()

### Média anual de volume de meses com bom desempenho 
Os válores são influenciados pela quantidade de meses negativos e positivos de um determinado ano. Caso um ano tenha mais meses negativos do que positivos, a tendencia é que a **média de volume anual de meses com bom desempenho** seja menor

In [ ]:
dataframe_positivo.groupby('ano')['volume'].mean()

### Média anual de variações

In [ ]:
dcmc_formatada['var%'] = dcmc_formatada['var%'].astype(float)

In [ ]:
dcmc_formatada.groupby('ano')['var%'].mean()

### Volume anual total

In [ ]:
dataframe_negativo.groupby('ano')['volume'].sum()

In [ ]:
dataframe_positivo.groupby('ano')['volume'].sum()

In [ ]:
desenvolvimento_volume = px.line(dcmc_formatada, x='data', y='volume', log_y=True)
desenvolvimento_volume

## 3. Formatação do dataset Coingecko

In [ ]:
dcoingecko

In [ ]:
dcoingecko_formatado = dcoingecko.rename(columns={'snapped_at':'Data', 'market_cap':'Marketcap', 'total_volume':'Volume'})

In [ ]:
dcoingecko_formatado[['Marketcap', 'Volume']] = dcoingecko_formatado[['Marketcap', 'Volume']].astype(int)

In [ ]:
dcoingecko_formatado['Horário'] = dcoingecko_formatado['Data'].str[11:]
dcoingecko_formatado['Data'] = dcoingecko_formatado['Data'].str[:10]

In [ ]:
dcoingecko_formatado

In [ ]:
dcoingecko_formatado.dtypes

In [ ]:
dcoingecko_formatado.iloc[1498]

In [ ]:
dcoingecko_formatado['Data'] = pd.to_datetime(dcoingecko_formatado['Data'])
dcoingecko_formatado['Data'] = pd.to_datetime(dcoingecko_formatado['Data'], format = '%Y.%m.%d')

In [ ]:
dcoingecko_formatado['mês'] = dcoingecko_formatado['Data'].dt.month
dcoingecko_formatado['ano'] = dcoingecko_formatado['Data'].dt.year

In [ ]:
dcoingecko_formatado[(dcoingecko_formatado.mês == 8) & (dcoingecko_formatado.ano == 2024)]

In [ ]:
dcoingecko_formatado[dcoingecko_formatado['ano'] == 2025]

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
dfmensal = dcoingecko_formatado.groupby(['Data'])['Volume'].mean().reset_index()
dfmensal

In [ ]:
figura = px.line(dfmensal, x='Data', y='Volume', log_y=True)
figura

In [ ]:
dcmc_formatada['var%'] = dcmc_formatada['var%'].astype(float)
dcmc_formatada

In [ ]:
dcmc_formatada.to_parquet('dcmc dataset.parquet')